class DataIngestionArtifact:...
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerConfigArtifact:...
class ModelEvalutionConfigArtifact:...
class ModelPusherConfigArtifact:...


